---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge-mapping-development
  namespace: development
spec:
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-challenge-development-service.development

---
apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-development-service
  namespace: development
spec:
  ports:
    - port: 80
      targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
