---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge-mapping-production
  namespace: production
spec:
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-challenge-production-service.production

---
apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-production-service
  namespace: production
spec:
  ports:
    - port: 80
      targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
