---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge-mapping-staging
  namespace: staging
spec:
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-challenge-staging-service.staging

---
apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-staging-service
  namespace: staging
spec:
  ports:
    - port: 80
      targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
