apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: staging.domain.com
  namespace: staging
spec:
  secretName: staging.domain.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - staging.domain.com
