apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: domain.com
  namespace: production
spec:
  secretName: domain.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - domain.com
