apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: development.domain.com
  namespace: development
spec:
  secretName: development.domain.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - development.domain.com
