apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: development.domain.com
  namespace: development
spec:
  acmeProvider:
    authority: 'https://acme-v02.api.letsencrypt.org/directory'
    email: anish.mourya5@gmail.com
  ambassadorId:
    - default
  hostname: development.domain.com
  selector:
    matchLabels:
      hostname: development.domain.com
  tlsSecret:
    name: development.domain.com



