apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: domain.com
  namespace: production
spec:
  acmeProvider:
    authority: 'https://acme-v02.api.letsencrypt.org/directory'
    email: anish.mourya5@gmail.com
  ambassadorId:
    - default
  hostname: domain.com
  selector:
    matchLabels:
      hostname: domain.com
  tlsSecret:
    name: domain.com



